"""empty message

Revision ID: d9d7ed96ea6f
Revises: b37886fb5859
Create Date: 2022-03-08 16:41:39.974781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d7ed96ea6f'
down_revision = 'b37886fb5859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tlf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tlf', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
